# Uncomment the next line to define a global platform for your project
platform :ios, ‘8.0’

target 'SinaSwiftPractice' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SinaSwiftPractice
pod 'SnapKit’, ‘~>3.0.2’
pod ‘AFNetworking’
pod ’SVProgressHUD’
pod ’SDWebImage’
pod ‘YYModel’
end
